version: 2.1
jobs:
  staging:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout

  deploy:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |-
              git fetch
              git checkout master
              git merge staging
              git commit -m "merge from staging to prod"
              git push origin master

workflows:
  build-test-deploy:
    jobs:
      - staging
      - manual:
          type: approval
          requires: 
            - staging
      - deploy:
          requires: 
            - manual