workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - test:
          branches: 
            only:
              - staging
          docker:
            - image: circleci/node:10.15.0
          working_directory: ~/repo
          steps:
            - checkout