version: 2
jobs:
  - build:
      branches: 
        only:
          - staging
      docker:
        - image: circleci/node:10.15.0
      working_directory: ~/repo
      steps:
        - checkout

  - deploy:
      branches: 
        only:
          - staging
      docker:
        - image: circleci/node:10.15.0
      working_directory: ~/repo
      steps:
        - checkout