version: 2.1
jobs:
  test1:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout

  deploy:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout

workflows:
  build-test-deploy:
    jobs:
      - test1
      - deploy:
          requires: 
            - test1