version: 2.1
jobs:
  staging:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout

  deploy:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |-
              git config --global user.email "mateenah.connect@gmail.com"
              git config --global user.name "Mateenah"
              git fetch
              git checkout master
              echo "checked out master"
              git merge staging
              echo "merged master"
              echo "committed"
              echo "${ssh_key} > id_rsa"
              echo "ssh-add id_rsa"
              git push origin master
              echo "pushed to master"

workflows:
  build-test-deploy:
    jobs:
      - staging
      - manual:
          type: approval
          requires:
            - staging
      - deploy:
          requires:
            - manual
