version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout

workflows:
  build-test-deploy:
    jobs:
      - staging:
          type: approval
      - deploy:
          requires: 
            - staging