version: 2.1
jobs:
  staging:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout

  deploy:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "16:32:82:65:05:60:e4:06:60:61:6a:9d:d4:84:0a:4b"
      - run:
          command: |-
              git config --global user.email "mateenah.connect@gmail.com"
              git config --global user.name "Mateenah"
              git fetch
              git checkout master
              git merge staging
              echo "merged master"
              git push origin master
              echo "pushed to master"

workflows:
  build-test-deploy:
    jobs:
      - staging
      - manual:
          type: approval
          requires:
            - staging
      - deploy:
          requires:
            - manual
